# Generated by Django 4.2.14 on 2024-07-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_data_container_projects_owner_id_data_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_items',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.data_container'),
        ),
        migrations.AlterField(
            model_name='data_items',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data_items',
            name='item_name',
            field=models.TextField(null=True),
        ),
    ]
