# Generated by Django 4.2.14 on 2024-07-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_data_items_container_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_container',
            old_name='container_id',
            new_name='container_ID',
        ),
        migrations.RenameField(
            model_name='data_container',
            old_name='itemx',
            new_name='item_x',
        ),
        migrations.RenameField(
            model_name='data_container',
            old_name='itemy',
            new_name='item_y',
        ),
        migrations.RenameField(
            model_name='data_container',
            old_name='projectID',
            new_name='project_ID',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='owner_id',
            new_name='owner_ID',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectID',
            new_name='project_ID',
        ),
    ]
