# Generated by Django 4.2.14 on 2024-07-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_rename_item_x_data_container_container_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container_relation',
            old_name='relation_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='data_container',
            old_name='container_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='data_container',
            old_name='container_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='data_items',
            old_name='item_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='data_items',
            old_name='item_description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='container_relation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='container_relation',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='data_items',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='public',
        ),
        migrations.AddField(
            model_name='container_relation',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_relations', to='projects.data_container'),
        ),
        migrations.AddField(
            model_name='container_relation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container_relation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_relations', to='projects.data_container'),
        ),
        migrations.AddField(
            model_name='container_relation',
            name='project_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='data_container',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_container',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='data_container',
            name='prequisit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by', to='projects.data_container'),
        ),
        migrations.AddField(
            model_name='data_items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
