# Generated by Django 4.2.14 on 2024-08-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_relation_id_container_relation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container_relation',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='projects.data_container'),
        ),
        migrations.AlterField(
            model_name='container_relation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='projects.data_container'),
        ),
        migrations.AlterField(
            model_name='data_container',
            name='prequisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by', to='projects.data_container'),
        ),
    ]
