# Generated by Django 4.2.14 on 2024-08-16 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_alter_container_relation_child_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_container',
            options={'ordering': ['level', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='container_relation',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='projects.data_container'),
        ),
        migrations.AlterField(
            model_name='container_relation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='projects.data_container'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
