# Generated by Django 4.2.14 on 2024-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_topic_relations_topics_delete_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
